//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bsk.Site.Cliente
{
    public partial class pagamento_pix
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl nrcotacao;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl nomePix;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl email;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl cpf;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl telefone;
        protected global::System.Web.UI.HtmlControls.HtmlButton btnAlterar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl valor;
        protected global::System.Web.UI.HtmlControls.HtmlButton btnGerarPix;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lbMsg;
        protected global::System.Web.UI.WebControls.Label lblApiResponse;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pixQrCodeContainer;
        protected global::System.Web.UI.HtmlControls.HtmlImage imgPixQrCode;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pixCopyPaste;
        protected global::System.Web.UI.WebControls.Label lblPixStatus;
    }
}
